version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - MONGO_HOST=db-1

  db:
    image: mongo
    ports:
      - 27017:27017